interface with `scipy` (updated version)
artofscience/SAOR pull request #94
Opened 2021-08-26 09:58 UTC by Giannis1993

This PR includes a wrapper function for `scipy`.  Related link can be found below:
https://docs.scipy.org/doc/scipy/reference/tutorial/optimize.html#constrained-minimization-of-multivariate-scalar-functions-minimize
One thing I am not 100% sure about is why defining the inequality constraints as a `NonlinearConstraint` object (instead of a dictionary that is currently implemented) gives a warning but still works. Note that, according to the above link, one can define it both ways.
```python
ineq_cons = optimize.NonlinearConstraint(self.constraints, -np.inf, 0, jac=self.constraints_der)
solution = optimize.minimize(self.objective, x0, bounds=bounds, method='trust-constr',
                                     jac=self.objective_der, constraints=ineq_cons, options={'gtol': 1e-6})
```

2021-08-30 10:34 UTC, Giannis1993 commented on tests/solvers/test_solvers.py
> +    mysolver_scipy = SCIPY(problem_scipy.n, problem_scipy.m)
@artofscience this is how it looks like when i remove the class. Imo it is less readable compared to its current state. Note that the presence of `objective`, `objective_der`, etc. is required (I think); see below:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html
The issue is that you need to pass with `*args` the `problem` object to the aforementioned (required) functions.

```python
## Imports
from scipy import optimize

"""
This is a wrapper class to use the SCIPY optimization library found in the following link:
https://docs.scipy.org/doc/scipy/tutorial/optimize.html#constrained-minimization-of-multivariate-scalar-functions-minimize.
Requires an installation of ``scipy``.
"""


def scipy_solver(problem, **kwargs):
    """
        This method solves the approximate problem P:

        minimize

        .. math::

            \\tilde{g}_0^{(k)}[mathbf{x}]

        subject to

        .. math::

            \\tilde{g}_j^{(k)}[mathbf{x}] \\leq 0  ,  j = 1, ..., m \\\\
            \\x_min_i^{(k)} \\leq  x_i \\leq  \\x_max_i^{(k)}  ,  i = 1, ..., n \\\\

        Input:  problem
        Output: x
        """

    problem = problem
    x0 = kwargs.get('x0', 0.5*(problem.x_min + problem.x_max))
    bounds = optimize.Bounds(problem.x_min, problem.x_max)
    # ineq_cons = optimize.NonlinearConstraint(constraints, -np.inf, 0, jac=constraints_der)
    ineq_cons = {'type': 'ineq',
                 'fun' : constraints,
                 'jac' : constraints_der,
                 'args': (problem.g, problem.dg)}
    method = kwargs.get('method', 'SLSQP')
    options = kwargs.get('options', None)
    solution = optimize.minimize(objective, x0, args=(problem.g, problem.dg), bounds=bounds, method=method,
                                 jac=objective_der, constraints=ineq_cons, options=options)
    return solution.x


def objective(x, *args):
    return args[0](x)[0]


def objective_der(x, *args):
    return args[1](x)[0]


def constraints(x, *args):
    """ The minus sign is there because inequality constraints must be in the form g_j >= 0."""
    return -args[0](x)[1:]


def constraints_der(x, *args):
    """ The minus sign is there because inequality constraints must be in the form g_j >= 0."""
    return -args[1](x)[1:]
```

2021-08-30 11:18 UTC, MaxvdKolk commented on setup.py
> -        'cvxopt',
Yes, it would be nice if we can keep `cvxopt` (and others) as optional dependencies. When someone wants to run with those routines, they can add `cvxopt` to the local environment, or use possible feature flags when installing with `pip install`. 

It would be nice though, to ensure the imports of `cvxopt` raise a clear warning when the package is not available on the system and that it is needed for the specific part of SAOR. For instance, something like

```python
try:
    import some_package
except ImportError:
    raise Exception(
        "Package 'some_package' is not available in the current environment. "
        "Install 'some_package' or install SAOR with feature flags '...'."
    )
```

2021-08-30 11:35 UTC, MaxvdKolk commented on tests/solvers/test_solvers.py
> +    mysolver_scipy = SCIPY(problem_scipy.n, problem_scipy.m)
We could consider to define the functions locally and pass problem as a whole through `args`? In that way the extra functions are local to the `scipy_solver` function (so we will not call them by accident from elsewhere) and we have access to the whole problem instance (although g, dg might be sufficient). Maybe that unpacking `*args` help with readability, e.g. `problem, *_ = args`? 

```python
def scipy_solver(problem, **kwargs):
    def objective(x, *args):
        problem, *_ = args
        return problem.g(x)[0]

    def jacobian(x, *args):
        problem, *_ = args
        return problem.dg(x)[1:]

    # other functions
   
    optimize.minimize(objective, args=(problem), jacobian=jacobian, ...)
```

2021-08-31 13:11 UTC, Giannis1993 commented
After this is approved, I can change the files in the `examples/...` directory as well.

2021-09-02 07:00 UTC, artofscience commented on tests/solvers/test_solvers.py
> +    mysolver_scipy = SCIPY(problem_scipy.n, problem_scipy.m)
> @artofscience this is how it looks like when i remove the class. Imo it is less readable compared to its current state. Note that the presence of `objective`, `objective_der`, etc. is required (I think); see below:
> https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html
> The issue is that you need to pass with `*args` the `problem` object to the aforementioned (required) functions.
> 
> ```python
> def scipy_solver(problem, **kwargs):
>     problem = problem
>     x0 = kwargs.get('x0', 0.5*(problem.x_min + problem.x_max))
>     bounds = optimize.Bounds(problem.x_min, problem.x_max)
>     # ineq_cons = optimize.NonlinearConstraint(constraints, -np.inf, 0, jac=constraints_der)
>     ineq_cons = {'type': 'ineq',
>                  'fun' : constraints,
>                  'jac' : constraints_der,
>                  'args': (problem.g, problem.dg)}
>     method = kwargs.get('method', 'SLSQP')
>     options = kwargs.get('options', None)
>     solution = optimize.minimize(objective, x0, args=(problem.g, problem.dg), bounds=bounds, method=method,
>                                  jac=objective_der, constraints=ineq_cons, options=options)
>     return solution.x
> 
> 
> def objective(x, *args):
>     return args[0](x)[0]
> 
> 
> def objective_der(x, *args):
>     return args[1](x)[0]
> 
> 
> def constraints(x, *args):
>     """ The minus sign is there because inequality constraints must be in the form g_j >= 0."""
>     return -args[0](x)[1:]
> 
> 
> def constraints_der(x, *args):
>     """ The minus sign is there because inequality constraints must be in the form g_j >= 0."""
>     return -args[1](x)[1:]
> ```
> 
> There are probably some workarounds to make `problem` available to those functions, but I guess @MaxvdKolk and @aatmdelissen might already know them.

I would propose something like:

"""
def scipy_solver(problem, **kwargs):
    problem = problem
    x0 = kwargs.get('x0', 0.5*(problem.x_min + problem.x_max))
    bounds = optimize.Bounds(problem.x_min, problem.x_max)
    # ineq_cons = optimize.NonlinearConstraint(constraints, -np.inf, 0, jac=constraints_der)
    ineq_cons = {'type': 'ineq',
                 'fun' : constraints,
                 'jac' : constraints_der,
                 'args': (problem.g, problem.dg)}
    method = kwargs.get('method', 'SLSQP')
    options = kwargs.get('options', None)
    solution = optimize.minimize(objective, x0, args=(problem.g, problem.dg), bounds=bounds, method=method,
                                 jac=objective_der, constraints=ineq_cons, options=options)
    return solution.x


def objective(x, *args):
    return args[0](x)[0]


def objective_der(x, *args):
    return args[1](x)[0]


def constraints(x, *args):
    """ The minus sign is there because inequality constraints must be in the form g_j >= 0."""
    return -args[0](x)[1:]


def constraints_der(x, *args):
    """ The minus sign is there because inequality constraints must be in the form g_j >= 0."""
    return -args[1](x)[1:]

"""

2021-09-02 07:10 UTC, artofscience requested changes

2021-09-02 07:10 UTC, artofscience commented on sao/solvers/scipy_wrapper.py
> +    return solution.x
```suggestion
    """
        This function solves a given problem P:

        minimize

        .. math::

            \\tilde{g}_0^{(k)}[mathbf{x}]

        subject to

        .. math::

            \\tilde{g}_j^{(k)}[mathbf{x}] \\leq 0  ,  j = 1, ..., m \\\\
            \\x_min_i^{(k)} \\leq  x_i \\leq  \\x_max_i^{(k)}  ,  i = 1, ..., n \\\\

        Input:  problem
        Output: x
        """
        
    # TODO: Possibly add diagonal Hessian that we currently have (they use a full Hessian with different dimensions)

    x0 = kwargs.get('x0', 0.5*(problem.x_min + problem.x_max))
    bounds = optimize.Bounds(problem.x_min, problem.x_max)
    # ineq_cons = optimize.NonlinearConstraint(constraints, -np.inf, 0, jac=constraints_der)
    ineq_cons = {'type': 'ineq',
                 'fun' : @(x) -problem.g(x)[1,:],
                 'jac' : @(x) -problem.dg(x)[1,:],
                 'args': (problem, Ellipsis)}
    method = kwargs.get('method', 'SLSQP')
    options = kwargs.get('options', None)
    solution = optimize.minimize(@(x) problem.g(x)[0], x0, args=(problem, Ellipsis), bounds=bounds, method=method,
                                 jac=@(x) problem.dg(x)[0], constraints=ineq_cons, options=options)
    return solution.x
```

2021-09-12 12:38 UTC, Giannis1993 commented on sao/solvers/scipy_wrapper.py
> +    return solution.x
looks simple and neat; Shall we merge? @artofscience @MaxvdKolk

2021-09-12 12:40 UTC, artofscience commented on sao/solvers/scipy_wrapper.py
> +    return solution.x
It is not tested yet, but indeed it looks good

2021-09-12 12:45 UTC, Giannis1993 commented on sao/solvers/scipy_wrapper.py
> +    return solution.x
aight, i ll test it and if it passes i ll push n merge.

2021-09-12 13:25 UTC, Giannis1993 commented on sao/solvers/scipy_wrapper.py
> +    return solution.x
Wrote it like that; i think it is a bit more readable:
```python
x0 = kwargs.get('x0', 0.5*(problem.x_min + problem.x_max))
    bounds = optimize.Bounds(problem.x_min, problem.x_max)
    objective = lambda x: problem.g(x)[0]
    objective_der = lambda x: problem.dg(x)[0]
    constraints = lambda x: -problem.g(x)[1:]
    constraints_der = lambda x: -problem.dg(x)[1:]
    # TODO: Possibly add diagonal Hessian that we currently have (they use a full Hessian with different dimensions)

    ineq_cons = {'type': 'ineq',
                 'fun': constraints,
                 'jac': constraints_der,
                 }
    method = kwargs.get('method', 'SLSQP')
    options = kwargs.get('options', None)
    solution = optimize.minimize(objective, x0, bounds=bounds, method=method,
                                 jac=objective_der, constraints=ineq_cons, options=options)
    return solution.x
```

2021-09-12 14:35 UTC, merged